### ISSUE TITLE
Wifi接続でアクセスポイントが検出されない

### ISSUE THREAD

**Issue by nichiyoubi** [nichiyoubi/model_checking_exercise#7]
LEGO Mindstorms EV3にWifiドングルを接続して、Wifi接続を試みましたが、宇佐美の家の環境ではアクセスポイント（WiFiルーター）が認識されません。
近所のWifiルーターは検出されますので、環境問題と思われます。

環境は、以下の通りです。

WiFiドングル：ONKYO製 UWF-1
WiFiルーター：Buffalo製 WHR-1166DHP

**Comment by tohosokawa** [comment]
もう少し情報が欲しいので質問です。
1. ドングルをPCに刺した場合は認識、接続できますか？
2. ルータの設定でSSIDが見えないようにしていませんか？
3. PC、スマートフォンなどからは5GHz, 2.4GHzのSSIDの両方とも見えていますか？

**Comment by nichiyoubi** [comment]
回答します。
1. ドングルをPCに刺した場合は認識、接続できますか？
   　　試していません。出張中のため、後日確認してみます。
2. ルータの設定でSSIDが見えないようにしていませんか？
   　　していません。
3. PC、スマートフォンなどからは5GHz, 2.4GHzのSSIDの両方とも見えていますか？
   　　あ、これかもしれません。
   　　思い返すと・・・自宅のMacBook Pro、iPhone6S+からは、11a(5GHz)だけ見えているかも。
   　　UWF-1は2.4GHｚ（11b/g ?）だけ対応かもしれません。

**Comment by tohosokawa** [comment]
UWF-1は2.4GHz(11n/b/g)だけみたいなので、本当に2.4GHzのSSIDがMacとかから見えていないようだと、きっとつながらないですね。

ルータ自体は5GHzと2.4GHzを同時に使えるようですので、設定を見直す必要があるかもしれません。

あとは、SSIDは見えているので大丈夫だと思いますが、組み込みとかのプアなOSだとANY接続を拒否しているルータに繋げないことがあるの注意が必要です。

**Comment by k-ishii-n** [comment]
こちらでは、以下の環境で、Ｗｉｆｉ接続できました。

（１）
　Wifiドングル：Buffalo製 WLI-UC-GNM2
　Wifiルーター：NEC製 AtermWR4100N

（２）
　Wifiドングル：Buffalo製 WLI-UC-GNM2
　Wifiルーター：SAMSUNG製 GALAXY S5 SCL23(テザリング)

**Comment by nichiyoubi** [comment]
Buffalo製 WHR-1166DHPのファームウェアをアップデートしたら、認識するようになりました。
（おかげさまで、Macの方も認識するようになってハッピーです！）
